name: CI Pipeline

on: [push]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./web_app
        run: |
          {
            echo "$(date) INFO [Install] Starting dependencies installation"
            pip install -r requirements.txt
            echo "$(date) INFO [Install] Dependencies installed"
          } 2>&1 | tee install.log

      - name: Run tests
        working-directory: ./web_app
        run: |
          {
            echo "$(date) INFO [Test] Starting tests"
            pytest -v || echo "$(date) ERROR [Test] Some tests failed"
            echo "$(date) INFO [Test] Finished tests"
          } 2>&1 | tee tests.log

      - name: Deploy (mock)
        working-directory: ./web_app
        run: |
          {
            echo "$(date) INFO [Deploy] Deploying app"
            sleep 3
            echo "$(date) INFO [Deploy] Deployment complete"
          } 2>&1 | tee deploy.log

      - name: Merge logs into single file
        working-directory: ./web_app
        run: |
          cat install.log tests.log deploy.log > pipeline.log
          echo "$(date) INFO [Pipeline] Pipeline finished" >> pipeline.log

      - name: Send pipeline log to ELK
        working-directory: ./web_app
        run: |
          curl -XPOST "${{ secrets.NGROK_URL }}" \
               -H "Content-Type: text/plain" \
               --data-binary @pipeline.log
